ishwar46/jhapalisamajapi

controller/adminController.js
controller/uploadController.js
controller/userController.js
index.js
middleware/authMiddleware.js
middleware/uploader.js
models/User.js
models/deletedUser.model.js
routes/adminRoutes.js
routes/uploadRoutes.js
routes/userRoutes.js

Auth Added with Image and File Upload

Auth Added with Image and File Upload

---

controllers/programsController.js
index.js
models/programsPage.js
routes/programsRoutes.js

Program and Initiatives added

---

controllers/testimonialsController.js
index.js
models/testimonials.js
routes/testimonialsRoutes.js

Testimonials CRUD added

---

controllers/blogController.js
index.js
models/Blog.js
routes/blogRoutes.js

Blogs Controller Added

---

controllers/missionStoryController.js
controllers/storyPageController.js
database/db.js
index.js
middleware/adminMiddleware.js
models/missionStory.js
models/storyPage.js
routes/missionStroryRoutes.js
routes/storyRoutes.js

Mission and Stories CRUD Added

Mission and Stories

---

controllers/scholarshipController.js
controllers/scholarshipRecipientsController.js
index.js
models/scholarshipPage.js
models/scholarshipRecipientsPage.js
routes/scholarshipRecipientsRoutes.js
routes/scholarshipRoutes.js

Scholarship page added with CRUD

Scholarship page added with CRUD

---

controllers/hearseVehicleController.js
index.js
models/hearseVehiclePage.js
routes/hearseVehicleRoutes.js

Hearse Vehicle Contributions page added with CRUD

Hearse Vehicle Contributions page added with CRUD

---

controllers/executiveCommitteeController.js
index.js
models/executiveCommitteePage.js
routes/executiveCommitteeRoutes.js

executive-committee crud added

executive-committee crud added

---

controllers/annualDonationController.js
index.js
models/annualDonationPage.js
routes/annualDonationRoutes.js

Annual Donation Page with Data and CRUD

Annual Donation Page with Data and CRUD

---

controllers/dmvChapterController.js
index.js
models/DMVChapterPage.js
routes/dmvChapterRoutes.js

Washington DC, Virginia & Maryland Chapter CRUD

Washington DC, Virginia & Maryland Chapter

---

controllers/texasChapterController.js
index.js
models/texasChapterPage.js
routes/texasChapterRoutes.js

Texas Chapter CRUD added

---

controllers/documentController.js
index.js
middleware/uploader.js
models/documentPage.js
routes/documentRoutes.js

documents api added

---

controllers/userController.js
models/User.js
utils/Validators.js

validators added

---

controllers/presidentMessageController.js
controllers/settingsController.js
index.js
models/Settings.js
models/presidentsMessage.js
routes/documentRoutes.js
routes/presidentMessageRouter.js
routes/settingsRoute.js

Modify backend to implement dynamic settings and president message

Modify backend to make page dynamic

---

controllers/userController.js
models/User.js
routes/executiveCommitteeRoutes.js
routes/userRoutes.js
utils/RandomPass.js
utils/emailTemplates.js

Setup support for random password and backend for executive

Setup support for random password

---

controllers/userController.js
utils/RandomPass.js
utils/emailTemplates.js

Generated passwords now at least have one uppercase, lowercase, number and special character

Added a better password generation algorithm

---

index.js
models/Donation.js
package-lock.json
package.json
routes/donationRoutes.js
routes/webhookRoutes.js
utils/donationReceiptEmail.html

Stripe Integration Done

---

controllers/adminController.js
controllers/uploadController.js
controllers/userController.js
middleware/nodeMailer.js
models/Counter.js
models/User.js
package.json
routes/uploadRoutes.js
utils/emailTemplates.js
utils/getNextReceiptNumber.js

Added new email and updated added support for new account status, membership receipt upload, counter.

Qol and upload routes config

---

controllers/newsLetterController.js
controllers/noticeController.js
controllers/userController.js
index.js
models/NewsLetter.js
models/Notice.js
routes/newsLetterRoutes.js
routes/noticeRoutes.js
routes/userRoutes.js

Added support for notice and newsletter

Add support for notice and newsletter

---

controllers/attendeeController.js
index.js
models/AttendeePage.js
routes/attendeeRoutes.js
utils/emailTemplates.js

Added backend support for event attendee registration

Attendee registration backend

---

controllers/attendeeController.js
models/AttendeePage.js

edit attendee api

---

controllers/attendeeController.js
models/AttendeePage.js
routes/attendeeRoutes.js

Added support for affiliates and images

Add support for affiliates and images

---

controllers/attendeeController.js
index.js
models/AttendeePage.js
routes/attendeeRoutes.js
utils/emailTemplates.js

Added more data to attendee page and updated the email template

Attendee page and email template update

---

controllers/adminController.js
controllers/attendeeController.js
middleware/volunteerMiddleware.js
models/AttendeePage.js
models/User.js
routes/adminRoutes.js
routes/userRoutes.js

Added volunteer and QR Scanner backend

Changes for event

---

routes/attendeeRoutes.js

volunteers can now GET all attendees

Volunteer route access update

---

controllers/attendeeController.js
models/AttendeePage.js
routes/attendeeRoutes.js
utils/emailTemplates.js

Get specific attendee
